// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxkVB3B31uLFTt6qcVeHhXE2TT4sBdpz0',
    appId: '1:542521113627:web:47ad3ec1e17ba97e104cbe',
    messagingSenderId: '542521113627',
    projectId: 'foodit-8ec9b',
    authDomain: 'foodit-8ec9b.firebaseapp.com',
    storageBucket: 'foodit-8ec9b.appspot.com',
    measurementId: 'G-VP21K61RX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz-njxId2IgCkM6kZGTzul9gB4HHkzjtQ',
    appId: '1:542521113627:android:1d9ac0bdf48f92f9104cbe',
    messagingSenderId: '542521113627',
    projectId: 'foodit-8ec9b',
    storageBucket: 'foodit-8ec9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNvh6reKUyhMTwxe3NE5dGwatObtHS01M',
    appId: '1:542521113627:ios:e83f7ba97e23194d104cbe',
    messagingSenderId: '542521113627',
    projectId: 'foodit-8ec9b',
    storageBucket: 'foodit-8ec9b.appspot.com',
    iosClientId: '542521113627-ncqk6r4f7cr9mtqo80ic25avtp9em01g.apps.googleusercontent.com',
    iosBundleId: 'com.shrijalshr.foodit.foodit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNvh6reKUyhMTwxe3NE5dGwatObtHS01M',
    appId: '1:542521113627:ios:e83f7ba97e23194d104cbe',
    messagingSenderId: '542521113627',
    projectId: 'foodit-8ec9b',
    storageBucket: 'foodit-8ec9b.appspot.com',
    iosClientId: '542521113627-ncqk6r4f7cr9mtqo80ic25avtp9em01g.apps.googleusercontent.com',
    iosBundleId: 'com.shrijalshr.foodit.foodit',
  );
}
