// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrTbLhjokmGam_NNcUA6a5I4ukroFMvgs',
    appId: '1:725677244060:web:eddd7dbd3bf034791ef759',
    messagingSenderId: '725677244060',
    projectId: 'foodit-380509',
    authDomain: 'foodit-380509.firebaseapp.com',
    storageBucket: 'foodit-380509.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRhEy35LjLh2GyTBtAYGkhRKIuwoiGi0g',
    appId: '1:725677244060:android:abec04a0015ffc2a1ef759',
    messagingSenderId: '725677244060',
    projectId: 'foodit-380509',
    storageBucket: 'foodit-380509.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhI6ksQfX3cSV4RkXaUYThfTpT-rlPoGk',
    appId: '1:725677244060:ios:e65b9bd44711fd0e1ef759',
    messagingSenderId: '725677244060',
    projectId: 'foodit-380509',
    storageBucket: 'foodit-380509.appspot.com',
    androidClientId: '725677244060-hm2obpk3bpre17245960omepmoatbhnn.apps.googleusercontent.com',
    iosClientId: '725677244060-9ucciial5qhdjbe87h3p8r4blbcar15k.apps.googleusercontent.com',
    iosBundleId: 'com.shrijalshr.foodit.foodit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhI6ksQfX3cSV4RkXaUYThfTpT-rlPoGk',
    appId: '1:725677244060:ios:e65b9bd44711fd0e1ef759',
    messagingSenderId: '725677244060',
    projectId: 'foodit-380509',
    storageBucket: 'foodit-380509.appspot.com',
    androidClientId: '725677244060-hm2obpk3bpre17245960omepmoatbhnn.apps.googleusercontent.com',
    iosClientId: '725677244060-9ucciial5qhdjbe87h3p8r4blbcar15k.apps.googleusercontent.com',
    iosBundleId: 'com.shrijalshr.foodit.foodit',
  );
}
